# 개발 로컬 환경의 Docker
version: "3.9"
services: 
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE_APP}
      network: host # alpine build 중 temporary error 방지.
    ports:
      - ${APP_PORT_EXTERNAL}:80
    # depends_on:
    #  db:
    #    condition: service_completed_successfully
    volumes:
      - ./app:/srv/app
      - ./scripts:/srv/scripts
      - ./djangobasekit/docker/docker-entrypoint.sh:/srv/docker-entrypoint.sh
      # - webapp_data:/app/web
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /bin/bash /srv/docker-entrypoint.sh
  db:
    # mariadb LTS 버전 10.6 (2026-07), 10.11 (2028-02)
    image: mariadb:10.11
    environment: 
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT_EXTERNAL}:3306
    volumes:
      - db:/var/lib/mysql
    restart: always
volumes:
  db:
